// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info is the result of an update check, shaped for the frontend.
 */
export interface Info {
    "currentVersion": string;
    "latestVersion": string;
    "updateAvailable": boolean;
    "releaseURL": string;
    "releaseNotes": string;
    "assetURL": string;
    "checksumsURL": string;
}
