// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the service exposed to the frontend. Every exported method is callable
 * from JavaScript through the generated bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetServices returns the current service snapshot.
 */
export function GetServices(): $CancellablePromise<$models.Service[] | null> {
    return $Call.ByID(839930963);
}

/**
 * HideWindow hides the popover panel (used by the footer close button).
 */
export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(542966029);
}

/**
 * Scan re-runs auto-detection and rebuilds the service list.
 */
export function Scan(): $CancellablePromise<void> {
    return $Call.ByID(2265593888);
}

/**
 * StartAll starts every controllable, stopped service.
 */
export function StartAll(): $CancellablePromise<void> {
    return $Call.ByID(1593724210);
}

/**
 * StopAll stops every controllable, running service.
 */
export function StopAll(): $CancellablePromise<void> {
    return $Call.ByID(1829082188);
}

/**
 * Toggle starts or stops the named service.
 */
export function Toggle(id: string): $CancellablePromise<void> {
    return $Call.ByID(1190013837, id);
}
