// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is a single controllable (or observable) local AI service.
 */
export interface Service {
    /**
     * unique snake_case key e.g. "ollama"
     */
    "ID": string;

    /**
     * display name e.g. "Ollama"
     */
    "Name": string;

    /**
     * how it is detected / controlled
     */
    "Kind": ServiceKind;

    /**
     * systemctl unit name (KindSystemctl only)
     */
    "Unit": string;

    /**
     * docker container name (KindDocker only)
     */
    "Container": string;

    /**
     * primary port for display / port probing
     */
    "Port": number;

    /**
     * current observed state
     */
    "Running": boolean;

    /**
     * Tabler icon name without the "ti-" prefix
     */
    "Icon": string;

    /**
     * "green" | "blue" | "amber" | "purple" | "gray" | "pink"
     */
    "Color": string;

    /**
     * one-line status shown below the name in the card
     */
    "Meta": string;

    /**
     * true = auto-detected, not in the hardcoded list
     */
    "Auto": boolean;
}

/**
 * ServiceKind describes how a service is detected and controlled.
 */
export enum ServiceKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Linux only
     */
    KindSystemctl = "systemctl",

    /**
     * both platforms
     */
    KindDocker = "docker",

    /**
     * auto-detected via TCP probe, read-only
     */
    KindPort = "port",
};
