// Package polkit generates and installs the polkit rule that lets
// administrative-group users manage Helm's systemd system units without a password.
// This is the polished alternative to the README's NOPASSWD sudoers setup:
// the service engine tries plain (polkit-governed) systemctl first, so once
// this rule is installed no sudo configuration is needed. Docker, port, and
// process kinds never go through polkit; user units (systemctl --user) need
// no privilege at all.
package polkit

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"helm/internal/service"
)

// RulePath is the production install target.
const RulePath = "/etc/polkit-1/rules.d/99-helm.rules"

// unitName normalizes a unit to its full name ("ollama" -> "ollama.service";
// names already carrying a suffix pass through untouched).
func unitName(u string) string {
	if strings.Contains(u, ".") {
		return u
	}
	return u + ".service"
}

// SystemUnits extracts the deduplicated systemd system-unit names the rule
// must allow, in service order, from a merged service snapshot.
func SystemUnits(services []service.Service) []string {
	var units []string
	seen := map[string]bool{}
	for _, s := range services {
		if s.Kind != service.KindSystemctl || s.Unit == "" {
			continue
		}
		u := unitName(s.Unit)
		if !seen[u] {
			seen[u] = true
			units = append(units, u)
		}
	}
	return units
}

// GenerateRule renders the JavaScript polkit rule for the given units. The
// rule is deliberately narrow: only the org.freedesktop.systemd1.manage-units
// action, only the standard wheel/sudo administrator groups, only the listed
// units, and only
// start/stop/restart verbs.
func GenerateRule(units []string) string {
	quoted := make([]string, 0, len(units))
	for _, u := range units {
		quoted = append(quoted, fmt.Sprintf("%q", u))
	}
	return fmt.Sprintf(`// Generated by helm-cli setup-polkit — regenerate after changing your
// services with: sudo helm-cli setup-polkit
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.systemd1.manage-units" &&
        (subject.isInGroup("wheel") || subject.isInGroup("sudo"))) {
        var unit = action.lookup("unit");
        var verb = action.lookup("verb");
        var allowedUnits = [%s];
        var allowedVerbs = ["start", "stop", "restart"];
        if (allowedUnits.indexOf(unit) >= 0 && allowedVerbs.indexOf(verb) >= 0) {
            return polkit.Result.YES;
        }
    }
});
`, strings.Join(quoted, ", "))
}

// Install writes the rule to path with 0644 permissions, creating parent
// directories as needed. The path is a parameter (production callers pass
// RulePath) so tests never touch /etc; writing the real path requires root.
func Install(path, rule string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(rule), 0o644)
}
